[package]
name = "tbox"
version = "1.0.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
clap = { version = "4.5.29", features = ["cargo"] }
colored = "3.0.0"
crossterm = "0.28.1"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
